"""
Turns data/community_centers.json into a self-contained mobile-first HTML page.

"Open now" is computed here at generation time in Seattle local time (not
client-side), same reasoning as the pools/wading-pools generators: this page
is meant to be regenerated by a scheduled job, so "is it open right now" has
to be baked in rather than trusted to whatever timezone a reader's browser
thinks it's in.

Not every center's hours could be parsed into a structured per-weekday
open/close time (the scraper already tried its best and gives up per-center
rather than guessing) - those centers get is_open_now = None here rather
than a guessed True/False, and the card falls back to showing the raw hours
text instead of an "Open now"/"Closed now" pill. Same "don't overclaim
precision" posture as the rest of this repo.
"""
import json
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data" / "community_centers.json"
OUT_PATH = ROOT / "site" / "index.html"
DOCS_OUT = ROOT.parent / "docs" / "community-centers" / "index.html"

SEATTLE_TZ = ZoneInfo("America/Los_Angeles")
WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

# Canonical neighborhood bucket order for the filter dropdown - independent
# of whatever order centers happen to appear in the data.
BUCKET_ORDER = [
    ("ballard-fremont-greenwood", "Ballard / Fremont / Greenwood"),
    ("wallingford-green-lake", "Wallingford / Green Lake"),
    ("north-seattle", "North Seattle"),
    ("northeast-seattle", "Northeast Seattle"),
    ("queen-anne-magnolia", "Queen Anne / Magnolia"),
    ("downtown-slu", "Downtown / South Lake Union"),
    ("capitol-hill-central-district", "Capitol Hill / Central District"),
    ("west-seattle", "West Seattle"),
    ("southeast-seattle", "Southeast Seattle"),
    ("georgetown-south-park", "Georgetown / South Park"),
    ("other", "Other Seattle"),
]


def fmt_time(hhmm: str) -> str:
    h, m = hhmm.split(":")
    h, m = int(h), int(m)
    ap = "am" if h < 12 else "pm"
    h12 = h % 12
    h12 = 12 if h12 == 0 else h12
    return f"{h12}:{m:02d}{ap}" if m else f"{h12}{ap}"


def build_center_view(center: dict, weekday: str, now_minutes: int):
    hours_parsed = center.get("hours_parsed")
    is_open_now = None
    today_label = None

    if hours_parsed is not None:
        today = hours_parsed.get(weekday)
        if today is None:
            is_open_now = False
            today_label = "Closed today"
        else:
            open_h, open_m = map(int, today["open"].split(":"))
            close_h, close_m = map(int, today["close"].split(":"))
            open_min = open_h * 60 + open_m
            close_min = close_h * 60 + close_m
            is_open_now = open_min <= now_minutes <= close_min
            today_label = f"{fmt_time(today['open'])}–{fmt_time(today['close'])} today"

    return {
        **center,
        "is_open_now": is_open_now,
        "today_label": today_label,
    }


def render(data: dict) -> str:
    now = datetime.now(SEATTLE_TZ)
    weekday = WEEKDAYS[now.weekday()]
    now_minutes = now.hour * 60 + now.minute

    centers = [build_center_view(c, weekday, now_minutes) for c in data["centers"]]
    centers.sort(key=lambda c: c["name"])

    present_buckets = {c["neighborhood_bucket"] for c in centers}
    neighborhood_options = [
        {"value": slug, "label": label}
        for slug, label in BUCKET_ORDER
        if slug in present_buckets
    ]

    parsed_ok = sum(1 for c in centers if c.get("hours_parsed"))

    view = {
        "generated_at": now.strftime("%A, %B %-d at %-I:%M %p") + " Pacific",
        "date_label": now.strftime("%A, %B %-d"),
        "hub_url": data["hub_url"],
        "teen_programs_url": data.get("teen_programs_url"),
        "centers": centers,
        "neighborhood_options": neighborhood_options,
        "low_confidence": parsed_ok < len(centers) * 0.6,
    }

    template = (Path(__file__).parent / "template.html").read_text(encoding="utf-8")
    return template.replace("__CENTER_DATA__", json.dumps(view))


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    html = render(data)
    OUT_PATH.write_text(html, encoding="utf-8")
    DOCS_OUT.parent.mkdir(parents=True, exist_ok=True)
    DOCS_OUT.write_text(html, encoding="utf-8")
    print(f"Wrote {OUT_PATH} and {DOCS_OUT}")


if __name__ == "__main__":
    main()
